### PR TITLE
Submodule's dir named after artifactId

### PR DESCRIPTION
**Pull request by manandbytes**
Hi there! One more fix, this time for #7 (partially, for android-release only). To make it easier to review, I've made @c3c22d08 as a separate commit because it fixes an indentation only. It may be even thrown away at all.

### CODE REVIEW

**Comment by cescoffier** [comment]
Hi,

This looks pretty good. Could you do the same for the integration-test archetype ? I will merge into the master branch (and probably release it afterwards).

**Comment by manandbytes** [comment]
Yup, I'll be back in couple days.

**Comment by manandbytes** [comment]
Actually, these changes deprecate an android-archetypes-it module. It may be removed at all but I'm not sure if it make sense to move asserts from QuickstartArchetypeTest, ReleaseArchetypeTest and WithTestsArchetypeTest into a post-build hook script, http://maven.apache.org/plugins/maven-invoker-plugin/examples/post-build-script.html

**Comment by cescoffier** [comment]
Hi,

Why does it 'deprecate' the integration tests ? They are run after the archetypes themselves, to should not be an issue. We just have to update the tests to match the new structure. no ?

**Comment by manandbytes** [comment]
Sorry, my previous comment really belongs to #18.

**Pull request merged**
